### ISSUE TITLE
fullPaths: true

### ISSUE THREAD

**Issue by fabiooshiro** [BigstickCarpet/simplifyify#20]
Hi,

How can I pass the flags to browserify?
Im trying to user discify and I got this error:

Error: Please recompile this browserify bundle using the --full-paths flag (when using the command-line interface) or with the fullPaths option set to true (when using the JavaScript API).

**Comment by BigstickCarpet** [comment]
Hi @fabiooshiro,
To specify flags, you'll have to use the Browserify CLI directly.  Simplifyify is meant to be an opinionated tool for using Browserify in a few specific common scenarios, so it intentionally doesn't expose all of Browserify's functionality or arguments.
