### ISSUE TITLE
source map outputs '\\' but not '/' in the sources path list on Windows

### ISSUE THREAD

**Issue by benxshen** [BigstickCarpet/simplifyify#4]
Here is my simple gulpfile, just copying from the given sample of simplifyify README.md:

```
var gulp        = require("gulp"),
    simplifyify = require("simplifyify");   // https://www.npmjs.com/package/simplifyify

gulp.task("browserify", function(done) {
  simplifyify("app.js",
    {
        outfile: "bundle.js",
        debug: true,
        minify: true
    })
    // .on("end", function() {
    //     // Finished successfully!
    //     done();
    // })
    .on("error", function(err) {
        // Something went wrong
        done(err);
    });
});
```

And the output of the bundle.js.map as below (my OS is Windows 10 64bit)

```
  "version": 3,
  "sources": [
    "node_modules\\browserify\\node_modules\\browser-pack\\_prelude.js",
    "app.js",
    "buttons\\button.js",
    "node_modules\\jquery\\dist\\jquery.js"
  ],
  ...
```

however, if I use `browserify app.js --debug | exorcist bundle.js.map > bundle.js`, I will get as follow:

```
  "version": 3,
  "sources": [
    "node_modules/browserify/node_modules/browser-pack/_prelude.js",
    "app.js",
    "buttons/button.js",
    "node_modules/jquery/dist/jquery.js"
  ],
  ...
```

I think the output path of the source with '\' will be not correct when I deploy them to the server. Is it a bug? or where can I have an option to make the path separator to '/', but not system default sep '\'?

Thank you.

**Comment by BigstickCarpet** [comment]
I think you're right, that this is a bug.  When I get a chance, I'll look into it further to confirm whether it's a bug and get it fixed.  Thanks for reporting it!

**Comment by BigstickCarpet** [comment]
I looked into this further, and I honestly don't know whether it's a bug or not.  The source maps are created by [Exorcist](https://github.com/thlorenz/exorcist), which in-turn uses [mold-source-map](https://github.com/thlorenz/mold-source-map).  That's where the backslashes are coming from.  So, it may be a bug in mold-source-map, or it may _not_ be a bug at all.  I don't know the details of the source map spec, so I can't say for sure.

**Comment by BigstickCarpet** [comment]
I'm gonna' go ahead and close this issue, since I'm not sure if it's actually a bug or not.  If it _is_ a bug, then it's a bug in [mold-source-map](https://github.com/thlorenz/mold-source-map)
