### ISSUE TITLE
Uglifyjs options

### ISSUE THREAD

**Issue by aristidesfl** [BigstickCarpet/simplifyify#6]
Is it possible to pass options to uglifyjs?
I'm trying to acomplish the same as [`cross-env NODE_ENV=production browserify src/main.js | uglifyjs -c warnings=false -m > dist/build.js`](https://github.com/vuejs-templates/browserify-simple/blob/master/template/package.json#L10)

**Comment by BigstickCarpet** [comment]
That's not currently possible, mostly to keep things simple.  (sorry, I know this is pretty much the same answer as I gave [here](https://github.com/BigstickCarpet/simplifyify/issues/5#issuecomment-183368402).

**Comment by BigstickCarpet** [comment]
I just released version 3.0.0, which now allows you to configure uglifyify via the `browserify.transform` field in the `package.json`.  See the example [here](https://github.com/BigstickCarpet/simplifyify#browserify-transforms)
